### ISSUE TITLE
Implementation To-do

### ISSUE THREAD

**Issue by matheuspor** [matheuspor/mma-fights-web-scraper#1]
### Tasks by priority

- [ ] Implements mongoose, add a model to the Fights table, a service layer and a controller layer.
- [ ] Save the scraped data in the mongoDB Forms table.
- [ ] Add unit tests to the model, service and controller layer in the /fights route.
- [ ] Add E2E tests in the /fights route.

### Future development

Scrape and create another table containing the full fight card in the current event and the main fighters snapshot photo.
