### ISSUE TITLE
/api/fights-card route implementation

### ISSUE THREAD

**Issue by matheuspor** [matheuspor/mma-fights-web-scraper#6]
### Tasks by priority

- [x] Implements a scrape function returning the fight card of each fight in the Fights table. #7 
- [x] Implements a model, service layer and a controller layer to handle the scraped data in the FightsCard table. #8 
- [x] Add unit tests to the model, service and controller layer in the /fights-card route. #9 
- [x] Add E2E tests in the /fights-card route. #10
